name: 'action-tag-date-version'
description: 'Automatically add a tag with a date version'
author: 'Francesco Novy'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  prerelase:
    description: 'If set, tag the version as prerelease - set to e.g. alpha or beta'
    required: false
