name: action-tag-date-version

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: action-tag-date-version
        uses: ./ # Uses an action in the root directory
        id: action-tag-date-version
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
