name: action-tag-date-version

on: [push]

jobs:
  tag-version:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: action-tag-date-version
        uses: ./ # Uses an action in the root directory
        id: action-tag-date-version
